---
triggers:
  comment:
    # Basic match
    - content: 'Approve me :)'

    # Regex
    - content: '^Hello[,\s]world!?$'
      regex: true

    # Inverse
    - content: 'Don't approve me :('
      inverse: true

  description:
    # Request changes unless all checkboxes are checked
    - content: '^- ?\[ \]'
      regex: true
      inverse: true

comment: 'Reviewed it!'
